import product1 from './assets/images/products/products1.jpg';
import product2 from './assets/images/products/products2.jpg';
import product3 from './assets/images/products/products3.jpg';
import product4 from './assets/images/products/products4.jpg';
import product5 from './assets/images/products/products5.jpg';
import product6 from './assets/images/products/products6.jpg';
import product7 from './assets/images/products/products7.jpg';
import product8 from './assets/images/products/products8.jpg';
import product9 from './assets/images/products/products9.jpg';
import product10 from './assets/images/products/products10.jpg';
const products = [
  {
    Id: 1,
    Name: 'مانتو زنانه',
    SideGroupName: 'لباس زنانه',
    SideGroupErpCode: 12,
    SellPrice: 157000,
    LastBuyPrice: 20,
    Image: product1,
    MainGroupName: 'فروشگاه قاصدک',
    MainGroupErpCode: 10,
  },
  {
    Id: 2,
    Name: 'کت مردانه',
    SideGroupName: 'لباس مردانه',
    SideGroupErpCode: 12,
    SellPrice: 199000,
    LastBuyPrice: 0,
    Image: product2,
    MainGroupName: 'فروشگاه قاصدک',
    MainGroupErpCode: 10,
  },
  {
    Id: 3,
    Name: 'مانتو زنانه مدل هودی تیک تین',
    SideGroupName: 'لباس زنانه',
    SideGroupErpCode: 12,
    SellPrice: 135000,
    LastBuyPrice: 10,
    Image: product3,
    MainGroupName: 'فروشگاه قاصدک',
    MainGroupErpCode: 10,
  },
  {
    Id: 4,
    Name: 'مانتو زنانه',
    SideGroupName: 'لباس زنانه',
    SideGroupErpCode: 12,
    SellPrice: 145000,
    LastBuyPrice: 0,
    Image: product4,
    MainGroupName: 'فروشگاه قاصدک',
    MainGroupErpCode: 10,
  },
  {
    Id: 5,
    Name: 'مانتو زنانه',
    SideGroupName: 'لباس زنانه',
    SideGroupErpCode: 12,
    SellPrice: 170000,
    LastBuyPrice: 0,
    Image: product5,
    MainGroupName: 'فروشگاه قاصدک',
    MainGroupErpCode: 10,
  },
  {
    Id: 6,
    Name: 'مانتو زنانه',
    SideGroupName: 'لباس زنانه',
    SideGroupErpCode: 12,
    SellPrice: 185000,
    LastBuyPrice: 0,
    Image: product6,
    MainGroupName: 'فروشگاه قاصدک',
    MainGroupErpCode: 10,
  },
  {
    Id: 7,
    Name: 'تیشرت مردانه',
    SideGroupName: 'لباس مردانه',
    SideGroupErpCode: 12,
    SellPrice: 57000,
    LastBuyPrice: 0,
    Image: product7,
    MainGroupName: 'فروشگاه قاصدک',
    MainGroupErpCode: 10,
  },
  {
    Id: 8,
    Name: 'کت مردانه مجلسی مدل k-m-5110',
    SideGroupName: 'لباس مردانه',
    SideGroupErpCode: 12,
    SellPrice: 199000,
    LastBuyPrice: 0,
    Image: product8,
    MainGroupName: 'فروشگاه قاصدک',
    MainGroupErpCode: 10,
  },
  {
    Id: 9,
    Name: 'تیشرت مردانه',
    SideGroupName: 'لباس مردانه',
    SideGroupErpCode: 12,
    SellPrice: 60000,
    LastBuyPrice: 0,
    Image: product9,
    MainGroupName: 'فروشگاه قاصدک',
    MainGroupErpCode: 10,
  },
  {
    Id: 10,
    Name: 'پیرهن مردانه',
    SideGroupName: 'لباس مردانه',
    SideGroupErpCode: 12,
    SellPrice: 120000,
    LastBuyPrice: 10,
    Image: product10,
    MainGroupName: 'فروشگاه قاصدک',
    MainGroupErpCode: 10,
  },
  {
    Id: 11,
    Name: 'مانتو زنانه',
    SideGroupName: 'لباس زنانه',
    SideGroupErpCode: 12,
    SellPrice: 170000,
    LastBuyPrice: 0,
    Image: product5,
    MainGroupName: 'فروشگاه قاصدک',
    MainGroupErpCode: 10,
  },
  {
    Id: 12,
    Name: 'مانتو زنانه',
    SideGroupName: 'لباس زنانه',
    SideGroupErpCode: 12,
    SellPrice: 185000,
    LastBuyPrice: 0,
    Image: product6,
    MainGroupName: 'فروشگاه قاصدک',
    MainGroupErpCode: 10,
  },
  {
    Id: 13,
    Name: 'تیشرت مردانه',
    SideGroupName: 'لباس مردانه',
    SideGroupErpCode: 12,
    SellPrice: 57000,
    LastBuyPrice: 0,
    Image: product7,
    MainGroupName: 'فروشگاه قاصدک',
    MainGroupErpCode: 10,
  },
  {
    Id: 14,
    Name: 'کت مردانه مجلسی مدل k-m-5110',
    SideGroupName: 'لباس مردانه',
    SideGroupErpCode: 12,
    SellPrice: 199000,
    LastBuyPrice: 0,
    Image: product8,
    MainGroupName: 'فروشگاه قاصدک',
    MainGroupErpCode: 10,
  },
  {
    Id: 15,
    Name: 'تیشرت مردانه',
    SideGroupName: 'لباس مردانه',
    SideGroupErpCode: 12,
    SellPrice: 60000,
    LastBuyPrice: 0,
    Image: product9,
    MainGroupName: 'فروشگاه قاصدک',
    MainGroupErpCode: 10,
  },
];
export default products;
